POST http://localhost:8000/add
Content-Type: application/json

{
    "title" : "aller au sport",
    "note": "evfzvfjhevfjefefef",
    "etat" : "okay"
}

###
GET  http://localhost:8000/add
s
###
# Pour supprimer une task u suffit de rentrer son id a la fin de la ligne si dessous
DELETE http://localhost:8000/delete/44

###
# Pour supprimer une task u suffit de rentrer son id a la fin de la ligne si dessous
PUT http://localhost:8000/update/8
Content-Type: application/json

{
  "title": "modif task",
  "note": "on s'en fiche la note ne s'affiche pas",
  "etat": "modifié chef"
}