POST http://localhost:8000/add
Content-Type: application/json

{
    "title" : "aller au sport",
    "note": "evfzvfjhevfjefefef",
    "etat" : "okay"
}

###
GET  http://localhost:8000/add

###
DELETE http://localhost:8000/delete/10

###
PUT http://localhost:8000/update/10
Content-Type: application/json

{
  "title": "Updated Task 2",
  "note": "This is the updated description",
  "etat": "modifie"
}